version: '3'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile-webapi # Your web API Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlite

  sqlite:
    image: sqlite:latest
    volumes:
      - ./data:/data # Map the data directory to the host machine
